"""table alterations

Revision ID: 029f783a0cbc
Revises: 46ece57a2e30
Create Date: 2024-02-12 12:14:58.065145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '029f783a0cbc'
down_revision: Union[str, None] = '46ece57a2e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('category_polarity', sa.Integer(), nullable=False, server_default='-1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'category_polarity')
    # ### end Alembic commands ###
